Open gcode file in raw mode to avoid byte decoding issues
Example gcode file contains multibyte characters like "→"; reading the file
backwards in text mode causes byte decoding errors like:

    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 0: invalid start byte

Included test ensures correct operation.

Fixes #65